### ISSUE TITLE
Using 16kHz models

### ISSUE THREAD

**Issue by aidv** [gvne/vstSpleeter#2]
Is this possible?

I looked into `spleeterpp` code real quick but couldn't find anything that indicates which model is downloaded.

**Comment by gvne** [comment]
It needs a bit of adaptation but it should be fairly straightforward. Most of the work will be done on `spleeterpp`. I duplicated the issue there

**Comment by aidv** [comment]
@gvne Alright I'll have a look.

**Comment by gvne** [comment]
Using the spleeterpp v0.2 you should just have to add the `-Dspleeter_enable_high_resolution=ON` option to cmake commands.

**Comment by aidv** [comment]
@gvne It works great!
