### ISSUE TITLE
[Question] VS2019 and not 2017?

### ISSUE THREAD

**Issue by aidv** [gvne/vstSpleeter#8]
After solving issue #5 I followed the new steps of `vstSpleeter` and I noticed that the JUSE project states that VS2019 is used.

I thought that `spleeterpp` can only be built using VS2017 as stated in it's repository?

Would you like to clarify what's going on here?

**Comment by gvne** [comment]
Spleeterpp v0.1 use tensorflow_cc. This library is only compatible with VS2017. Now that the v0.2 uses the Tensorflow C api, VS2019 is supported. As it is always better to use an up to date compiler, I used 2019 the juce project

**Comment by aidv** [comment]
@gvne I'm glad you updated it. It works very well now.
