### ISSUE TITLE
Incomplete and invalid instructions? (Windows)

### ISSUE THREAD

**Issue by aidv** [gvne/vstSpleeter#9]
I'm following the instructions but I can see that some things seem to be invalid.

For example, the JUCE project states that Release Extra Compiler Flags contains `-I../external/spleeterpp/build/install/include`,
however, there is no `..../install` folder available after following your steps.

Did you run the commands using Git Bash as explained in #5?

Why does vstSpleeter JUCE file contain an export for VS2019, when spleeterpp strictly requires to be build with VS2017?

For me, I get the build error that says that `spleeter_common/spleeter_common.h` and `spleeter_filter/filter.h` doesn't exist.

**Comment by aidv** [comment]
You should replace some instructions with the following:

```
SPLEETERPP_INSTALL_DIR=$(pwd)/install <<<< missing
mkdir build && cd build
cmake -Drtff_use_mkl=ON -DCMAKE_INSTALL_PREFIX=$SPLEETERPP_INSTALL_DIR -G"Visual Studio 15 2017 Win64" .. <<<< missing
cmake --build . --target install --config Release
```

This at least created the `install` directory.

**Comment by aidv** [comment]
I also had to create a new export for VS2017 and copy all settings from VS2019.

On top of that I had to change Extra Compiler Flags to

```-I../../external/spleeterpp/install/include
-I../../external/eigen```

and Extra Linker Flags to

```../../external/spleeterpp/install/lib```

Now it built, but failed with `cannot open file 'tensorflow.lib'`

**Comment by aidv** [comment]
I also changed the Release Post-Build Command to

> if not exist "$(TargetDir)models" mkdir "$(TargetDir)models"
> xcopy "../../external/spleeterpp/install/models/filter" "$(TargetDir)models" /s /e /Y

**Comment by aidv** [comment]
Also, copying `tensorflow.dll` to System32 did nothing for me, I needed to copy the DLL to the DAW Host root path. This loaded the VST successfully in JUCE `AudioPluginHost`.

But crashed when trying to connect the VST to the output component in the editor.

**Comment by aidv** [comment]
It no longer crashed once I copied the "models" folder to the root of the VST `c:/program files/vstplugins/`.

However, the plugin is still unrecognized by Studio One.

**Comment by aidv** [comment]
It seems like Studio One is not even scanning the plugin. Hmmmm...

**Comment by gvne** [comment]
Does using the v0.2 tag of spleeterpp solve this ?

**Comment by aidv** [comment]
@gvne probably not. But it's nothing wrong with spleeterpp or vstSpleeter. I installed the VST in the wrong directory. So everything is good now.
